/********************************************************************
* EXITDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EXITDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEXITDict();
extern void G__cpp_setup_inheritanceEXITDict();
extern void G__cpp_setup_typetableEXITDict();
extern void G__cpp_setup_memvarEXITDict();
extern void G__cpp_setup_globalEXITDict();
extern void G__cpp_setup_memfuncEXITDict();
extern void G__cpp_setup_funcEXITDict();
extern void G__set_cpp_environmentEXITDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EXITMeasLayer.h"
#include "EXITFBMeasLayer.h"
#include "EXITKalDetector.h"
#include "EXITHit.h"
#include "EXITFBHit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EXITDictLN_TClass;
extern G__linked_taginfo G__EXITDictLN_TBuffer;
extern G__linked_taginfo G__EXITDictLN_TMemberInspector;
extern G__linked_taginfo G__EXITDictLN_TObject;
extern G__linked_taginfo G__EXITDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EXITDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EXITDictLN_TObjArray;
extern G__linked_taginfo G__EXITDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EXITDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__EXITDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EXITDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EXITDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__EXITDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__EXITDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__EXITDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__EXITDictLN_TVector3;
extern G__linked_taginfo G__EXITDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__EXITDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__EXITDictLN_TKalMatrix;
extern G__linked_taginfo G__EXITDictLN_TVTrack;
extern G__linked_taginfo G__EXITDictLN_TVSurface;
extern G__linked_taginfo G__EXITDictLN_TCylinder;
extern G__linked_taginfo G__EXITDictLN_TMaterial;
extern G__linked_taginfo G__EXITDictLN_TAttElement;
extern G__linked_taginfo G__EXITDictLN_TVTrackHit;
extern G__linked_taginfo G__EXITDictLN_TVMeasLayer;
extern G__linked_taginfo G__EXITDictLN_TAttDrawable;
extern G__linked_taginfo G__EXITDictLN_EXVMeasLayer;
extern G__linked_taginfo G__EXITDictLN_EXITMeasLayer;
extern G__linked_taginfo G__EXITDictLN_TPlane;
extern G__linked_taginfo G__EXITDictLN_EXITFBMeasLayer;
extern G__linked_taginfo G__EXITDictLN_TCollection;
extern G__linked_taginfo G__EXITDictLN_TSeqCollection;
extern G__linked_taginfo G__EXITDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EXITDictLN_TVKalDetector;
extern G__linked_taginfo G__EXITDictLN_EXVKalDetector;
extern G__linked_taginfo G__EXITDictLN_EXITKalDetector;
extern G__linked_taginfo G__EXITDictLN_EXITHit;
extern G__linked_taginfo G__EXITDictLN_EXITFBHit;

/* STUB derived class for protected member access */
