/********************************************************************
* EXVTXDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EXVTXDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEXVTXDict();
extern void G__cpp_setup_inheritanceEXVTXDict();
extern void G__cpp_setup_typetableEXVTXDict();
extern void G__cpp_setup_memvarEXVTXDict();
extern void G__cpp_setup_globalEXVTXDict();
extern void G__cpp_setup_memfuncEXVTXDict();
extern void G__cpp_setup_funcEXVTXDict();
extern void G__set_cpp_environmentEXVTXDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EXVTXKalDetector.h"
#include "EXVTXMeasLayer.h"
#include "EXVTXHit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EXVTXDictLN_TClass;
extern G__linked_taginfo G__EXVTXDictLN_TBuffer;
extern G__linked_taginfo G__EXVTXDictLN_TMemberInspector;
extern G__linked_taginfo G__EXVTXDictLN_TObject;
extern G__linked_taginfo G__EXVTXDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EXVTXDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EXVTXDictLN_TObjArray;
extern G__linked_taginfo G__EXVTXDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EXVTXDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__EXVTXDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EXVTXDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EXVTXDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__EXVTXDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__EXVTXDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__EXVTXDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__EXVTXDictLN_TVector3;
extern G__linked_taginfo G__EXVTXDictLN_TCollection;
extern G__linked_taginfo G__EXVTXDictLN_TSeqCollection;
extern G__linked_taginfo G__EXVTXDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EXVTXDictLN_TAttElement;
extern G__linked_taginfo G__EXVTXDictLN_TVKalDetector;
extern G__linked_taginfo G__EXVTXDictLN_TAttDrawable;
extern G__linked_taginfo G__EXVTXDictLN_TVMeasLayer;
extern G__linked_taginfo G__EXVTXDictLN_EXVKalDetector;
extern G__linked_taginfo G__EXVTXDictLN_EXVTXKalDetector;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__EXVTXDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__EXVTXDictLN_TKalMatrix;
extern G__linked_taginfo G__EXVTXDictLN_TVSurface;
extern G__linked_taginfo G__EXVTXDictLN_TCylinder;
extern G__linked_taginfo G__EXVTXDictLN_TMaterial;
extern G__linked_taginfo G__EXVTXDictLN_TVTrackHit;
extern G__linked_taginfo G__EXVTXDictLN_EXVMeasLayer;
extern G__linked_taginfo G__EXVTXDictLN_EXVTXMeasLayer;
extern G__linked_taginfo G__EXVTXDictLN_EXVTXHit;

/* STUB derived class for protected member access */
